### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Help12312** [Kr4ken-9/TatsumakiFarmer#100]
discord.errors.HTTPException: 400 Bad Request (error code: 0): <html><title>Error 400 (Bad Request)!!1</title></html>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DAD6B2D550>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
is where the error occurs help please

**Comment by Help12312** [comment]
tell me if u want me to send whole thing
